#!/usr/bin/env python3

'''
Highly divisible triangular number
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

https://projecteuler.net/problem=12
'''

import sympy.ntheory

def fact(number) :
	x = sympy.factorint(number)
	y = x.values()
	s = 1
	for num in y :
		s *= (num + 1)
	return s

def tri(number) :
	return (number * (number + 1)) / 2

n = 1
while fact(tri(n)) < 500 :
	n += 1

print(n)
print(tri(n))
