#!/usr/bin/env python3

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
'''


def solve(input_data):
    '''sum of the even-valued Fibo number below input_data
    https://projecteuler.net/problem=2
    :rtype: int
    '''
    a, b, c = 1, 2, 3
    result = 0
    while b < input_data:
        result += b
        a = b + c
        b = a + c
        c = a + b

    return result


def main():
    print(solve(4000000))


if __name__ == "__main__":
    main()
