#!/usr/bin/env python3

'''
Highly divisible triangular number
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

https://projecteuler.net/problem=12
'''

def num_factors(number):
    a= 2
    num = 1
    b = 0
    while number != 1:
        if number%a ==0:
            b +=1
            number = number /a
        else:
            num *=b+1
            b = 0
            a+=1
    return num*(b+1)

number = 1
i = 1
while num_factors(number) < 500:
    i+=1
    number += i
print(number)